jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout Repository (Your Repo)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone tunet-rust Repository
        run: |
          git clone https://github.com/Berrysoft/tunet-rust.git

      - name: Build Project
        working-directory: tunet-rust
        run: |
          cargo build --release --workspace --exclude native

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.platform }}  # 在artifact名称中加上平台名称
          path: tunet-rust/target/release/*
